---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ nginx_name }}-config
  namespace: {{ nginx_name }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="pl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{ nginx_title }}</title>
    </head>
    <body>
        <h1>{{ nginx_message }}</h1>
    </body>
    </html>
