---
apiVersion: v1
kind: Service
metadata:
  name: {{ nginx_name }}-service
  namespace: {{ nginx_name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ nginx_name }}
