---
- name: "Ensure dependencies are met"
  become: true
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present

- name: "Ensure manifest directory exists"
  ansible.builtin.file:
    path: "nginx"
    state: directory

- name: "Render templates to remote"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "nginx/{{ item | basename }}"
  with_fileglob:
    - "templates/*.yml"
    - "templates/*.yaml"

- name: "Find manifests on remote"
  ansible.builtin.find:
    path: nginx
    patterns: ['*.yml', '*.yaml']
  register: manifest_files

- name: "Apply Kubernetes resources"
  become: true
  kubernetes.core.k8s:
    state: "{{ nginx_state }}"
    src: "{{ item.path }}"
    kubeconfig: "{{ nginx_kubeconfig_location }}"
  loop: "{{ manifest_files.files }}"
  notify:
    - Manifests changed

